Add possibility to load more versions of dbc
BAndysc/WoWDatabaseEditor.Common pull request #1
Opened 2020-02-10 03:17 UTC by funjoker

Added possibility to load different versions of DBCs

2020-02-10 23:03 UTC, BAndysc requested changes
Firstly, thank you very much for the first contribution to the editor! It is very appreciated by everyone in wow private servers scene. I hope together we can develop the software :)

Apart from one note about enum, there is one more small thing: you have added file `Cata 4.3.4 (15595).xml` to Definitions folder, but you have to add it to the project in Visual Studio (so it is visible in Solution Explorer)
1. just drag and drop the file from Windows Explorer to the folder in Visual Studio (even though the file is already in that folder)
2. select the file in Visual Studio and in properties window of the file change `output` to `always copy`.

then, during build, the file will get copied to the appropriate folder.

I would be pleased if you could fix those things and then I can merge it :) Have a nice day!

2020-02-10 23:03 UTC, BAndysc commented on WDE.DbcStore/DbcStore.cs
> +        WOTLK_12340  = 12340,
Could you please either add definitions for Wratch or comment this enum value? At the moment there is no message this is unsupported, thus it may look like wotlk is supported, but in fact it is not :)

2020-02-11 06:38 UTC, funjoker commented on WDE.DbcStore/DbcStore.cs
> +        WOTLK_12340  = 12340,
Yeah my fault, will add definition for them

2020-02-11 06:55 UTC, funjoker commented
Btw, is the UNLICENSE license MIT compatible?
I may want to switch to a different DBC/DB2 reader which is more up to date.

2020-02-11 07:26 UTC, funjoker commented
Sadly, ItemTemplate needs to be loaded from mysql in wotlk.
I didn't check how this is done in this Editor

2020-02-11 10:56 UTC, BAndysc commented
About database, it is fairly easy, tho ATM items are not loaded at all, so apart from adding some code to DBCStore, definitions for items will have to be added.

Once item templates are loaded (analogically to CreatureTemplate), you just have to add `IDatabaseProvider database` argument to the constructor somewhere in DBCStore module, and this interface will have method `IEnumerble<IItemTemplate> GetItemTemplates()`. IItemTemplate will have properties int id and string name.

For other modules it will be transparent if it comes from DBC or database.

But let's leave that for other PR.
---

About the license, I have chosen the unlicense, because we know how wow private servers work and most of them do not care about license. But not to make problems with other libraries, it can be switched to MIT. 

I am open to changing DBC library. I have chosen that one, because it was one of few which could load Legion at the time. But it is really slow, so I don't see problems if we switched to something better. 

Thanks again for PR, later I will review the one in main repo :-) have a nice day!

2020-02-11 10:58 UTC, merged